### ISSUE TITLE
Ошибка Opkg::Manager: /opt/etc/ndm/netfilter.d/100-dns-local: exit code 1.

### ISSUE THREAD

**Issue by kilia07** [qzeleza/zezl#1]
Добрый день!
В системном журнале фиксируется ошибка:
Opkg::Manager: /opt/etc/ndm/netfilter.d/100-dns-local: exit code 1
При этом разблокировала сайтов работает штатно. 
Подобное наблюдаю на роутере c AdguardHome и без него. 
kvas debug с роутера без AdguardHome во вложении
[log_no_AdguardHome.zip](https://github.com/qzeleza/zezl/files/9838391/log_no_AdguardHome.zip)

**Comment by qzeleza** [comment]
А разве данная ошибка не относится к проекту Квас? 
Если так, то прошу Вас перенести данный Тикет в проект [Квас](https://github.com/qzeleza/kvas)
